### ISSUE TITLE
如果加入requirejs异步加载controller应该怎么处理？

### ISSUE THREAD

**Issue by L-Z-Y** [gusumuzhe/angular-ui-tabs#2]
作者你好，我是看到你的ui-tabs跟我目前的项目要求很匹配，准备替换掉现在的模式，但是我们目前用requirejs来异步加载js和html，我想问一下，应该怎么处理？

**Comment by gusumuzhe** [comment]
config分支的版本已经支持懒加载，你可以通过懒加载的方式异步加载js和html，最近我会抽个时间，完善一下说明文档

**Comment by L-Z-Y** [comment]
cnfig分支不会合并到master 是吗？

**Comment by gusumuzhe** [comment]
会合并到master的，config版本增加了类似ui-routes 的配置功能

**Comment by L-Z-Y** [comment]
如果用uirouter 那么会不会造成每个切换的时候都会刷新页面？
Chao Zhang <notifications@github.com>于2017年9月1日 周五18:30写道：

**Comment by gusumuzhe** [comment]
有参数设置，可以选择刷新，默认是不刷新的。而且并没有用uirouter，只是目前的ui-tabs 设置方式和ui-router 类似

**Comment by L-Z-Y** [comment]
config的代码已经合并到master了？

**Comment by L-Z-Y** [comment]
app.config(function (uiTabsProvider) {
    uiTabsProvider
        .tab('tab1', {
            title: 'tab1',
            controller: 'DemoController1',
            templateUrl: 'demo1.html',
            resolve: {
                deps: ['$ocLazyLoad',
                    function ($ocLazyLoad) {
                        return $ocLazyLoad.load([
                            'controller1.js']);
                    }]
            },
            params: {tab:1}
        })
        .tab('tab2', {
            title: 'tab2',
            controller: 'DemoController2',
            templateUrl: 'demo2.html',
            resolve: {
                deps: ['$ocLazyLoad',
                    function ($ocLazyLoad) {
                        return $ocLazyLoad.load([
                            'controller2.js']);
                    }]
            },
            params: {tab:2}
        });
})

deps:[]中加载js文件的代码是否可以通过requirejs加载

**Comment by gusumuzhe** [comment]
已经合并到master了，我并没有尝试过用requirejs加载，你可能需要将requirejs加载封装成Promise，可以参考这个[http://www.cnblogs.com/kenkofox/p/4643760.html](url)

**Comment by L-Z-Y** [comment]
好的，我觉得只要把 $ocLazyLoad.load(['controller2.js']);}]懒加载js的方式换成requirejs应该就行了，我尝试一下，感谢！

**Comment by L-Z-Y** [comment]
试了一下requirejs或者webpack的require.ensure还是不行，不知道是什么原因了?您能给看一下吗？
![image](https://user-images.githubusercontent.com/12064230/30152155-cdf1e922-93e4-11e7-9eaf-50099670f94e.png)
![image](https://user-images.githubusercontent.com/12064230/30152229-0d7548dc-93e5-11e7-9444-0fed3d665d4e.png)

**Comment by gusumuzhe** [comment]
```javascript
deps: function($q) {
  return $q(function(resolve) {
    require(['./controller1.js'], function(controller) {
      app.controller('DemoController1', controller);
      resolve(controller);
    })
  });
}
```
试下这个，主要的是封装成Promise

**Comment by L-Z-Y** [comment]
可以了，但是我发现页面里面如果有自定义directive模版的时候，往模版里面传参数的时候会拿不到？模版里面的数据是undefined

**Comment by gusumuzhe** [comment]
已修复

**Comment by L-Z-Y** [comment]
试了一下可以了，感谢，我再深入的用用看！
