### ISSUE TITLE
tab传参和tab也刷新的机制是通过什么实现的，您能给解释一下吗？

### ISSUE THREAD

**Issue by L-Z-Y** [gusumuzhe/angular-ui-tabs#3]

**Comment by L-Z-Y** [comment]
传参是通过controller动态注入的吗？tab刷新是怎么实现的？

**Comment by gusumuzhe** [comment]
传参是动态注入的，刷新是通过销毁旧的scope，重新生成一个新的scope，然后重新执行controller，完成刷新

**Comment by L-Z-Y** [comment]
好的，明白了，谢谢

**Comment by L-Z-Y** [comment]
您好，现在项目里面有2个子系统，每个子系统里面有不同的tab，我怎么在切换子系统后，重新去初始化tab列表，uiTabsProvider.tab()能重复执行吗？还有就是切换子系统的时候清空uiTabs后在打开一个tab，这个时候用uiTabs.closeAll()报错

**Comment by gusumuzhe** [comment]
uiTabsProvider.tab()，是在angular初始化的时候被执行，以后无法重复执行。uiTabs 你是怎么清空的？

**Comment by L-Z-Y** [comment]
直接调用的uiTabs.clsseAll()

**Comment by gusumuzhe** [comment]
你把报错信息发一下

**Comment by L-Z-Y** [comment]
![image](https://user-images.githubusercontent.com/12064230/30583256-163947ac-9d59-11e7-9475-2ac90aa04f67.png)
一共打开两个tab，切换子系统的时候调用uiTabs.closeAll()关闭目前的tab，然后切完子系统在open一个当前子系统的tab,子系统之间是通过uirouter切换的，每个路由作为一个子系统

**Comment by L-Z-Y** [comment]
好像是关闭还没完成，就又开始open的时候报错了，在open的时候外面套了一层timeout好像就可以了

**Comment by gusumuzhe** [comment]
有点不能理解为什么出现这个问题，closeAll 是一个同步的方法，即使立即打开新tab，也是得等closeAll 全部执行完，这个问题有时间我再仔细看看什么原因导致的

**Comment by L-Z-Y** [comment]
好，目前我只能先用$timeout(function(){uiTabs.open('新首页')})来解决了

**Comment by gusumuzhe** [comment]
我添加了判断，对于正在加载的tab，不执行销毁操作，你可以再试下
